[package]
name = "beer-backend"
version = "0.1.0"
authors = ["DorianXGH <dorian.bourgeoisat@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astro = "2.0.0"
chrono = "0.4"
serial = "0.4.0"